### ISSUE TITLE
Track satoshi client v0.12.0

### ISSUE THREAD

**Issue by evoskuil** [libbitcoin/libbitcoin-consensus#26]
This will eliminate the OpenSSL option, making secp256k1 non-optional.

This incorporates a flag for activating verification of BIP65's `OP_CHECKLOCKTIMEVERIFY`.

There are material changes to secp256k1, so this will create a dependency upgrade requirement for all libraries to a new secp256k1/version4 branch, and the need to update MSVC project/solution files for secp256k1.

**Comment by skaht** [comment]
Cool;-)

**Comment by evoskuil** [comment]
Complete in version2 [head]
